<a href="https://colab.research.google.com/github/Teja3993/Soft_Computing_Lab_exercises/blob/main/Soft_Computing_lab_21st_Jan_Percerceptron_Logical_Gates.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Define AND gate inputs and outputs
X_and = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y_and = np.array([0, 0, 0, 1])

# Perceptron Class
class Perceptron:
    def __init__(self, learning_rate=0.1, n_iterations=100):
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.weights = None
        self.bias = None

    def _step_function(self, x):
        return np.where(x >= 0, 1, 0)

    def fit(self, X, y):
        n_samples, n_features = X.shape

        # Initialize weights and bias
        self.weights = np.zeros(n_features)
        self.bias = 0

        for _ in range(self.n_iterations):
            for idx, x_i in enumerate(X):
                linear_output = np.dot(x_i, self.weights) + self.bias
                y_predicted = self._step_function(linear_output)

                # Perceptron learning rule
                update = self.learning_rate * (y[idx] - y_predicted)
                self.weights += update * x_i
                self.bias += update

    def predict(self, X):
        linear_output = np.dot(X, self.weights) + self.bias
        return self._step_function(linear_output)

# Create and train the Perceptron for AND gate
perceptron_and = Perceptron(learning_rate=0.1, n_iterations=10)
perceptron_and.fit(X_and, y_and)

# Test the Perceptron
predictions_and = perceptron_and.predict(X_and)

print("AND Gate Perceptron Results:")
print(f"Weights: {perceptron_and.weights}")
print(f"Bias: {perceptron_and.bias}")
print("\nInput (X):\n", X_and)
print("Target (y):\n", y_and)
print("Predicted (y_pred):\n", predictions_and)

# Check accuracy
accuracy = np.sum(predictions_and == y_and) / len(y_and)
print(f"\nAccuracy: {accuracy * 100:.2f}%")

AND Gate Perceptron Results:
Weights: [0.2 0.1]
Bias: -0.20000000000000004

Input (X):
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Target (y):
 [0 0 0 1]
Predicted (y_pred):
 [0 0 0 1]

Accuracy: 100.00%


### Perceptron Implementation using Functions and Loops (without classes)

In [5]:
import numpy as np

# Step function (activation function)
def step_function(x):
    return np.where(x >= 0, 1, 0)

# Function to train the perceptron
def train_perceptron(X, y, learning_rate=0.1, n_iterations=100):
    n_samples, n_features = X.shape
    weights = np.zeros(n_features)
    bias = 0

    for _ in range(n_iterations):
        for idx, x_i in enumerate(X):
            linear_output = np.dot(x_i, weights) + bias
            y_predicted = step_function(linear_output)

            update = learning_rate * (y[idx] - y_predicted)
            weights += update * x_i
            bias += update
    return weights, bias

# Function to predict using the trained perceptron
def predict_perceptron(X, weights, bias):
    linear_output = np.dot(X, weights) + bias
    return step_function(linear_output)

#### AND Gate Implementation

In [6]:
# Define AND gate inputs and outputs
X_and_func = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
y_and_func = np.array([0, 0, 0, 1])

# Train the perceptron for AND gate
weights_and, bias_and = train_perceptron(X_and_func, y_and_func, learning_rate=0.1, n_iterations=10)

# Test the Perceptron
predictions_and_func = predict_perceptron(X_and_func, weights_and, bias_and)

print("AND Gate Perceptron Results (Functional):")
print(f"Weights: {weights_and}")
print(f"Bias: {bias_and}")
print("\nInput (X):\n", X_and_func)
print("Target (y):\n", y_and_func)
print("Predicted (y_pred):\n", predictions_and_func)

# Check accuracy
accuracy_and_func = np.sum(predictions_and_func == y_and_func) / len(y_and_func)
print(f"\nAccuracy: {accuracy_and_func * 100:.2f}%")

AND Gate Perceptron Results (Functional):
Weights: [0.2 0.1]
Bias: -0.20000000000000004

Input (X):
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Target (y):
 [0 0 0 1]
Predicted (y_pred):
 [0 0 0 1]

Accuracy: 100.00%


#### OR Gate Implementation

In [7]:
# Define OR gate inputs and outputs
X_or_func = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
y_or_func = np.array([0, 1, 1, 1])

# Train the perceptron for OR gate
weights_or, bias_or = train_perceptron(X_or_func, y_or_func, learning_rate=0.1, n_iterations=10)

# Test the Perceptron
predictions_or_func = predict_perceptron(X_or_func, weights_or, bias_or)

print("OR Gate Perceptron Results (Functional):")
print(f"Weights: {weights_or}")
print(f"Bias: {bias_or}")
print("\nInput (X):\n", X_or_func)
print("Target (y):\n", y_or_func)
print("Predicted (y_pred):\n", predictions_or_func)

# Check accuracy
accuracy_or_func = np.sum(predictions_or_func == y_or_func) / len(y_or_func)
print(f"\nAccuracy: {accuracy_or_func * 100:.2f}%")

OR Gate Perceptron Results (Functional):
Weights: [0.1 0.1]
Bias: -0.1

Input (X):
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Target (y):
 [0 1 1 1]
Predicted (y_pred):
 [0 1 1 1]

Accuracy: 100.00%


#### XOR Gate Implementation

In [8]:
# Define XOR gate inputs and outputs
X_xor_func = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
y_xor_func = np.array([0, 1, 1, 0]) # XOR output

# Train the perceptron for XOR gate
weights_xor, bias_xor = train_perceptron(X_xor_func, y_xor_func, learning_rate=0.1, n_iterations=100) # Increased iterations

# Test the Perceptron
predictions_xor_func = predict_perceptron(X_xor_func, weights_xor, bias_xor)

print("XOR Gate Perceptron Results (Functional):")
print(f"Weights: {weights_xor}")
print(f"Bias: {bias_xor}")
print("\nInput (X):\n", X_xor_func)
print("Target (y):\n", y_xor_func)
print("Predicted (y_pred):\n", predictions_xor_func)

# Check accuracy
accuracy_xor_func = np.sum(predictions_xor_func == y_xor_func) / len(y_xor_func)
print(f"\nAccuracy: {accuracy_xor_func * 100:.2f}%")

if accuracy_xor_func < 1.0:
    print("\nAs expected, a single perceptron struggles with the XOR gate, as it's not linearly separable. This confirms the earlier observation.")

XOR Gate Perceptron Results (Functional):
Weights: [-0.1  0. ]
Bias: 0.0

Input (X):
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Target (y):
 [0 1 1 0]
Predicted (y_pred):
 [1 1 0 0]

Accuracy: 50.00%

As expected, a single perceptron struggles with the XOR gate, as it's not linearly separable. This confirms the earlier observation.


In [2]:
import numpy as np
import matplotlib.pyplot as plt
X_or = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y_or = np.array([0, 1, 1, 1])
# Create and train the Perceptron for OR gate
perceptron_or = Perceptron(learning_rate=0.1, n_iterations=10)
perceptron_or.fit(X_or, y_or)

# Test the Perceptron
predictions_or = perceptron_or.predict(X_or)

print("OR Gate Perceptron Results:")
print(f"Weights: {perceptron_or.weights}")
print(f"Bias: {perceptron_or.bias}")
print("\nInput (X):\n", X_or)
print("Target (y):\n", y_or)
print("Predicted (y_pred):\n", predictions_or)

# Check accuracy
accuracy_or = np.sum(predictions_or == y_or) / len(y_or)
print(f"\nAccuracy: {accuracy_or * 100:.2f}%")

OR Gate Perceptron Results:
Weights: [0.1 0.1]
Bias: -0.1

Input (X):
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Target (y):
 [0 1 1 1]
Predicted (y_pred):
 [0 1 1 1]

Accuracy: 100.00%


In [4]:
import numpy as np

# Define XOR gate inputs and outputs
X_xor = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y_xor = np.array([0, 1, 1, 0]) # XOR output

# Create and train the Perceptron for XOR gate
# Note: A single perceptron cannot perfectly solve XOR due to non-linear separability.
perceptron_xor = Perceptron(learning_rate=0.1, n_iterations=100) # Increased iterations to demonstrate more clearly
perceptron_xor.fit(X_xor, y_xor)

# Test the Perceptron
predictions_xor = perceptron_xor.predict(X_xor)

print("XOR Gate Perceptron Results:")
print(f"Weights: {perceptron_xor.weights}")
print(f"Bias: {perceptron_xor.bias}")
print("\nInput (X):\n", X_xor)
print("Target (y):\n", y_xor)
print("Predicted (y_pred):\n", predictions_xor)

# Check accuracy
accuracy_xor = np.sum(predictions_xor == y_xor) / len(y_xor)
print(f"\nAccuracy: {accuracy_xor * 100:.2f}%")

if accuracy_xor < 1.0:
    print("\nAs expected, a single perceptron struggles with the XOR gate, as it's not linearly separable.")
    print("To solve XOR, a multi-layer perceptron (neural network with hidden layers) is typically required.")

XOR Gate Perceptron Results:
Weights: [-0.1  0. ]
Bias: 0.0

Input (X):
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
Target (y):
 [0 1 1 0]
Predicted (y_pred):
 [1 1 0 0]

Accuracy: 50.00%

As expected, a single perceptron struggles with the XOR gate, as it's not linearly separable.
To solve XOR, a multi-layer perceptron (neural network with hidden layers) is typically required.
